# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Mdemh0BeGY43oebiX4QOMe59Hp09bVv

##Greeting Program
This script prompts for name and age, then outputs a personalized greeting
"""

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print(f"Hello, {name}! You are {age} years old. Welcome aboard!")

"""##Student Grades with Lists/Tuples
This program manages student records using lists of name-grade tuples, supporting add, view, and average calculations
"""

students = []
while True:
    print("\n1. Add Student  2. View All  3. Quit")
    choice = input("Choose: ")
    if choice == '3':
        break
    elif choice == '1':
        name = input("Name: ")
        grades = tuple(map(float, input("Enter grades (space-separated): ").split()))
        students.append((name, grades))
        print(f"Added {name}")
    elif choice == '2':
        if not students:
            print("No students.")
            continue
        for i, (name, grades) in enumerate(students, 1):
            avg = sum(grades) / len(grades)
            print(f"{i}. {name}: {grades} (Avg: {avg:.1f})")

"""#Grade Calculator Functions
Multiple functions handle input, average computation, letter grades, and reports.
"""

def get_grades():
    return list(map(float, input("Enter scores (space-separated): ").split()))

def calculate_average(grades):
    return sum(grades) / len(grades)

def get_letter_grade(avg):
    if avg >= 90: return 'A'
    elif avg >= 80: return 'B'
    elif avg >= 70: return 'C'
    elif avg >= 60: return 'D'
    return 'F'

def generate_report(grades):
    avg = calculate_average(grades)
    grade = get_letter_grade(avg)
    print(f"Average: {avg:.1f} ({grade}) {'Pass' if avg >= 60 else 'Fail'}")

grades = get_grades()
generate_report(grades)

"""#Dictionary-Only Library System
Tracks books solely via a dictionary (ISBN: {'title': str, 'author': str, 'copies': int}), with add/remove/search/update/report/stats.
"""

library = {}

def add_book():
    isbn = input("ISBN: ")
    if isbn in library:
        print("Book exists.")
        return
    library[isbn] = {
        'title': input("Title: "),
        'author': input("Author: "),
        'copies': int(input("Copies: "))
    }
    print("Added.")

def remove_book():
    isbn = input("ISBN: ")
    if isbn in library:
        del library[isbn]
        print("Removed.")
    else:
        print("Not found.")

def search_book():
    criteria = input("Search by (title/author/isbn): ")
    for isbn, info in library.items():
        if criteria.lower() in isbn or criteria.lower() in info['title'].lower() or criteria.lower() in info['author'].lower():
            print(f"{isbn}: {info['title']} by {info['author']} ({info['copies']} copies)")

def update_book():
    isbn = input("ISBN: ")
    if isbn in library:
        library[isbn]['title'] = input("New title (or enter): ") or library[isbn]['title']
        library[isbn]['author'] = input("New author (or enter): ") or library[isbn]['author']
        library[isbn]['copies'] = int(input("New copies: ") or library[isbn]['copies'])
        print("Updated.")
    else:
        print("Not found.")

def report():
    print(f"Total books: {len(library)}")
    total_copies = sum(info['copies'] for info in library.values())
    print(f"Total copies: {total_copies}")
    if library:
        avg_copies = total_copies / len(library)
        print(f"Avg copies/book: {avg_copies:.1f}")

while True:
    print("\n1.Add 2.Remove 3.Search 4.Update 5.Report 6.Quit")
    ch = input("Choose: ")
    if ch == '6': break
    elif ch == '1': add_book()
    elif ch == '2': remove_book()
    elif ch == '3': search_book()
    elif ch == '4': update_book()
    elif ch == '5': report()

"""#Smart To-Do & Habit Companion
Console app for tasks (add/view/done), habits (track streaks), and wellness insights from completion ratios/streaks—no file I/O, in-memory only.
"""

tasks = []  # list of str
task_done = 0
habits = {'Drink water': 0, 'Exercise': 0}  # habit: current_streak
max_streak = 0

while True:
    print("\n1.Add Task 2.View Tasks 3.Mark Task Done 4.Add Habit 5.View Habits 6.Daily Insight 7.Quit")
    choice = input("Choose: ")
    if choice == '7': break
    elif choice == '1':
        tasks.append(input("Task: "))
        print("Added.")
    elif choice == '2':
        for i, t in enumerate(tasks, 1):
            status = "✓" if i <= task_done else "○"
            print(f"{status} [{i}] {t}")
    elif choice == '3':
        num = int(input("Task #: "))
        if 1 <= num <= len(tasks):
            task_done = max(task_done, num)
            print("Marked done.")
    elif choice == '4':
        name = input("Habit: ")
        habits[name] = 0
        print("Added.")
    elif choice == '5':
        for h, streak in habits.items():
            print(f"{h}: {streak} days")
            max_streak = max(max_streak, streak)
    elif choice == '6':
        task_ratio = task_done / len(tasks) if tasks else 0
        score = (task_ratio * 50) + (max_streak * 5)
        if score >= 80: insight = "Excellent! Keep shining."
        elif score >= 50: insight = "Good progress. Stay consistent."
        else: insight = "Small steps today build big habits."
        print(f"Tasks: {task_done}/{len(tasks)}  Max streak: {max_streak}  Insight: {insight}")